---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Assert-More
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Carp::Assert: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.18
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Carp-Assert-More
  license: http://www.opensource.org/licenses/artistic-license-2.0.php
  repository: http://github.com/petdance/carp-assert-more/tree/master
version: 1.14
